#!/usr/bin/env bash

green=$(tput setaf 2)
reset=$(tput setaf 255)
red=$(tput setaf 9)

bin="./push_swap"
checker="./checker_linux"

max_range=9999999

test() {
	local num=$1
	local times=$2
	local min=99999
	local max=0
	local avg=0

	for ((i=0; i<times; i++)); do
		arg=$(shuf -i0-$max_range -n$num)
		op=$($bin $arg | wc -l)
		if ((op <= min)); then min=$op; fi
		if ((op >= max)); then max=$op; fi
		((avg+=$op))
	done

	printf "${green}======testing for $num random numbers $times times======${reset}\n"
	echo "average: " $((avg/$times))
	echo "min: " $min
	echo "max: " $max
	echo
}

main() {
	test 3 1000
	test 5 1000
	test 100 100
	test 500 100
}

main
